name: pr

on:
  push:
    paths:
      - 'tmp/*.apk'
    branches:
      - action-pr

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          branch: ${{ github.ref }}
          base: main
          title: '${{ github.event.head_commit.message }}'
          body: '${{ github.event.head_commit.message }}'
